### ISSUE TITLE
[1.12.2] Crash on dedicated servers

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/libVulpes#27] opened 2017-11-21 01:02 UTC
Libvulpes version 0.2.6-12 crashes as follows on dedicated servers:

https://pastebin.com/a3LWuF6t

This seems be caused by having converted the ISidedInventory to an IItemHandler, but not updating the methods you use in the astrobody data processor accordingly.

**Comment by zmaster587** [comment] 2017-11-21 04:02
dupe of https://github.com/zmaster587/AdvancedRocketry/issues/954 
should be fixed in latest build

**Closed by zmaster587** 2017-11-21 04:02 UTC
